from src.setting import *

OBST1_INTERVAL = 50
OBST2_INTERVAL = 50
OBST3_INTERVAL = 100
CACTUS_INTERVAL = 50
# 익룡을 더 자주 등장시키기 위해 12로 수정했습니다. (원래값은 300)
PTERA_INTERVAL = 12
CLOUD_INTERVAL = 300
OBJECT_REFRESH_LINE = width * 0.8
MAGIC_NUM = 10
GAME_SPEED = 4
SPEED_RATE = 1

LIFE = 5
BOSS_LIFE = 5
BOSS_LIFE_INCREASE_RATE = 1.2
BOSS_APPEARANCE_SCORE_RATE = 2
